### ISSUE TITLE
Webextension name locator is incorrect for firefox nightly.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/FoxPuppet#149]
Looking at the recent builds on travis-ci show an error caused by an element not being found, specifically this [line](https://github.com/mozilla/FoxPuppet/blob/master/foxpuppet/windows/browser/notifications/addons.py#L24). 

After doing some research it seems the notifications elements are now xul elements which will make things difficult to locate.

**Comment by jrbenny35** [comment]
Found the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1431242).

**Comment by davehunt** [comment]
This was uplifted to beta, so we're now failing across three channels. I'll look into it today.

**Comment by davehunt** [comment]
I've opened #152 to address this.

**Comment by jrbenny35** [comment]
Closed via #152
