### ISSUE TITLE
Bootstrap Script

### ISSUE THREAD

**Issue by silne30** [mozilla/FoxPuppet#18]
- [ ] Bootstrap Script
  - [ ] Set up pre-commit hook
  - [ ] Check to see if bash script or setup.py develop makes more sense

**Comment by davehunt** [comment]
@silne30 Can you add some more detail here. What would this script do?

**Comment by silne30** [comment]
It was a bootstrap script to configure your dev environment to be properly set up for hacking against this repo. I remember at one point there was supposed to be a pre-commit hook that would not allow a commit if flake8 failed. Stuff like that. But it seems that we went into a different direction with tox.

**Comment by davehunt** [comment]
pre-commit hooks are a good idea, but I don't think we need a script in the repo for this. If you have flake8 installed you can use `--install-hook=git`. I also don't think we need a bootstrap script as described. Tox takes care of most of what we need. The exception is downloading Firefox and geckodriver, but this is pretty simple and can be covered in our documentation.
