### ISSUE TITLE
Nightly and Developer Editions are failing in Travis CI

### ISSUE THREAD

**Issue by davehunt** [mozilla/FoxPuppet#194]
The Nightly builds have been failing in Travis CI since [12-08-2018](https://travis-ci.org/mozilla/FoxPuppet/builds/415006021), and Developer Edition has been failing since [29-08-2018](https://travis-ci.org/mozilla/FoxPuppet/builds/421855897). I was initially able to replicate locally (on macOS) but it turns out that might be an unrelated timing issue. It could be this 'regression' is only affecting Linux.

**Comment by jrbenny35** [comment]
Has this been fixed?

**Comment by davehunt** [comment]
Yes, thanks @jrbenny35, though I think I've seen some failures. Perhaps we have a flaky test. :/
