### ISSUE TITLE
Generate API documentation from source code

### ISSUE THREAD

**Issue by silne30** [mozilla/FoxPuppet#24]
We need to generate the API documentation from the source using docstrings. For this issue we should create an API page in the documentation that includes all public classes and methods with docstrings. We can then follow up with improving the structure and docstrings.

**Comment by davehunt** [comment]
@silne30 please open issues with a description as well as a title, otherwise it's hard for contributors to know what they need to work on or how to get started.

**Comment by davehunt** [comment]
You can see an example here: http://pypom.readthedocs.io/en/latest/api.html

**Comment by davehunt** [comment]
Landed in #67
