### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by b4handjr** [mozilla/FoxPuppet#308]
Currently there are some failing addon notification tests that can be seen [here](https://github.com/mozilla/FoxPuppet/actions). Please inspect the output and view the HTML report if needed.  There are a few things that need to be solved for the tests to work.

1. Update the `webserver.py` file. This is using an outdated way to host a webserver, we need to update this to current python 3.12 standards and recommendations. This is crucial for our tests.
2. Update the `webextension.xpi`. This XPI is quite old and it's format is outdated for modern web extensions. We need to create a new one that is compatible with modern Firefox.
3. Fix the tests. When the above is resolved we will still have some failing tests. One in particular `test_notification_with_origin` will need a change to the `notifications/base.py` page. 
4. Using the webserver to serve the XPI for certain tests is necessary to test the `AddOnInstallBlocked` notifications, but we need to also test this on Firefox release and versions that don't allow for unsigned extensions. 

All of these should be tested locally using `make test` and will need to pass on CI.

**Comment by Temidayo32** [comment]
I am looking into this issue
