### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by silne30** [mozilla/FoxPuppet#31]
This issue is to update our readme with more relevant information, badges for statuses of the build, usage and the overall purpose for FoxPuppet

**Comment by silne30** [comment]
We also may have a section that outlines the requirements for commits (Unit tests must cover code), etc.

**Comment by davehunt** [comment]
I think we can close this. We have badges and a summary in the README. A more detailed description would be good, but this can be done alongside the documentation. Also, we have coveralls for test coverage and Travis CI configured for pull requests.
