### ISSUE TITLE
Add mypy static type checking

### ISSUE THREAD

**Issue by b4handjr** [mozilla/FoxPuppet#314]
Let's add a static type checking tool to this project and get all of the classes and methods to be statically typed. We can use [mypy](https://mypy-lang.org/) for this since this is what we are mainly using at Mozilla.

- [ ] Add pyright to poetry and configure it in `pyproject.toml`
- [ ] Fix all objects and methods to be type checked
- [ ] Update test files to be type checked
- [ ] Add a command to the `Makefile` to run the static type checking
- [ ] Add a test to the github actions workflow to run the type checker on pull requests. 

Here are some basic options we should use my mypy, we can adjust these later as well. These should exist within the `pyproject.toml` file.

```
[tool.mypy]
python_version = "3.12"
disable_error_code = "attr-defined"
disallow_untyped_calls = false
follow_imports = "normal"
ignore_missing_imports = true
pretty = true
show_error_codes = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
warn_unreachable = true
```

**Comment by cashall-0** [comment]
hello @b4handjr , I would like to work on this. I'd try to do the type-checking.
