### ISSUE TITLE
Create Browser or Window Object

### ISSUE THREAD

**Issue by silne30** [mozilla/FoxPuppet#32]
- [ ] - Maximize Window
- [x] - Private Window
- [x] - New Window
- [x] - Unit Tests
- [x] - Docs

**Comment by whimboo** [comment]
Why do you want bookmark page as part of it? I don't see that as a general method for a browser window. We should better use the star button for that, which will be a subclass and unrelated to the browser window itself.

**Comment by silne30** [comment]
@whimboo Good call. I will make the edit. Seeing as how this is our first crack at this, I am sure we are going to have some confusion in implementation. Really appreciate you weighing in and helping us out.

**Comment by whimboo** [comment]
No problem at all. I know that the beginning is hard. And hashing out requirements together is always more productive and causes less issues upfront.

**Comment by davehunt** [comment]
> Maximize Window

Does it make sense to implement restore window too?

> Private Window

Is the intention to open a new window in private browsing mode, or is it an attribute that returns if the current window is in private browsing mode?

**Comment by silne30** [comment]
@davehunt The former. We want to open a new window in private mode. But that last use case may prove useful as well.

**Comment by whimboo** [comment]
> @davehunt The former. We want to open a new window in private mode. But that last use case may prove useful as well.

Well, that should be a property IMO on the browser class like `is_private`.

**Comment by davehunt** [comment]
This is done.
