### ISSUE TITLE
Enforce code coverage

### ISSUE THREAD

**Issue by b4handjr** [mozilla/FoxPuppet#323]
As this project grows, it will be great to use the pytest plugin `pytest-cov` to enforce code coverage. We will need to make a push to increase the coverage but adding a check to the CI runs to not allow a decrease in the current coverage would be great.

**Comment by cashall-0** [comment]
hello @b4handjr  for this issue, what particular percentage of coverage is the target that should be enforced?  the current coverage is about `Total coverage: 95.41%`

**Comment by b4handjr** [comment]
> hello @b4handjr for this issue, what particular percentage of coverage is the target that should be enforced? the current coverage is about `Total coverage: 95.41%`

Yeah, lets try and maintain that at least.

**Comment by cashall-0** [comment]
> > hello @b4handjr for this issue, what particular percentage of coverage is the target that should be enforced? the current coverage is about `Total coverage: 95.41%`
> 
> Yeah, lets try and maintain that at least.

I just made a pr for that.
