### ISSUE TITLE
Upgrade support to Python 3.6

### ISSUE THREAD

**Issue by davehunt** [mozilla/FoxPuppet#53]
We should make sure that FoxPuppet supports the latest stable version of Python. Let's also change the Travis CI jobs to run against 3.6 and update the documentation.

**Comment by jrbenny35** [comment]
Currently running into this issue. 

https://github.com/pypa/pypi-legacy/issues/322

If anyone could help that would be great.

**Comment by davehunt** [comment]
@jrbenny35 did you resolve your issue? I see you opened a pull request...
