### ISSUE TITLE
Addon Installation

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/FoxPuppet#68]
@silne30 brought this up to me yesterday. 

I think a way of specifying an addon to install and foxpuppet installs it would be cool. It would work right along with the notifications module we have now.

**Comment by davehunt** [comment]
This is already supported by allowing users to interact with notifications. There are just too many ways you might install an add-on, and too many variables, to add this directly into FoxPuppet. I just don't see the value. See https://github.com/mozilla/addons-server/compare/master...davehunt:e2e#diff-a42e92b4b666ce7c1aa49c55bcc916cfR12 for an example of how simple this already is with FoxPuppet.
