### ISSUE TITLE
Create Tracking Protection Shield object

### ISSUE THREAD

**Issue by rbillings** [mozilla/FoxPuppet#72]
When Tracking Protection is on, a shield displays in the toolbar.  An automated test needs to be written to verify the presence or absence of the shield icon.

**Comment by whimboo** [comment]
There are actually several places where the shield appears. As you say it is visible on the left side of the location bar, but there are also settings inside the identity popup. Given that we have slow progress on all that, you might better want to write this as a firefox-ui test those days. Especially if a test is urgent.

**Comment by jrbenny35** [comment]
@whimboo could you give me a link to where in marionette there is a test for this? Or maybe where it is used? I can't seem to find anything useful.

**Comment by whimboo** [comment]
You will have to look at least for the identity popup related tests in the firefox-ui subfolder. Not sure what is implemented as of today.

**Comment by jrbenny35** [comment]
@rbillings So I wrote something for this but there appears to be some difficulty determining if the shield is displayed or not. It looks like it is just hidden, and it doesn't have any css properties I can check for. Just wanted to give you an update.

**Comment by davehunt** [comment]
@jrbenny35 this could be related to [bug 1094246](https://bugzilla.mozilla.org/show_bug.cgi?id=1094246).

**Comment by jrbenny35** [comment]
Fixed in #92
